### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by williamn**
revert package definition to original after read this notice here https://packagist.org/packages/submit

Do not submit forks of existing packages. If you need to test changes to a package that you forked to patch, use VCS Repositories instead. If however it is a real long-term fork you intend on maintaining feel free to submit it.

so we will use VCS Repositories as instructed here https://getcomposer.org/doc/05-repositories.md#vcs

### CODE REVIEW

**Comment by rslhdyt** [comment]
@williamn kenapa di revert lagi name sama homepage nya Pak?

**Comment by williamn** [comment]
Baca commit message saya Sal

Thank you.

## 

_William Notowidagdo_
Think Big. Act small. Do now

**Comment by williamn** [comment]
@rslhdyt Baca commit message saya Sal. Buka juga Linknya.

**Comment by rslhdyt** [comment]
@williamn oke sorry Pak.

**Pull request merged**
